version: "3.9"
#cambio equis

services:
  db:
    image: mysql:8.0
    container_name: demo_mysql
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql           # DATOS persistentes
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # SQL inicial

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    container_name: demo_apache_php
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html                 # Tu c√≥digo local
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html

volumes:
  mysql_data:
